import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@radix-ui/themes/styles.css"
import { Theme, ThemePanel } from "@radix-ui/themes"
import { Providers } from '@/redux/provider'
import Navber from '@/components/navbar/Navber'
import AuthContext from '@/context/AuthContext'
import { ToastContainer} from 'react-toastify';
import DownPlayer from '@/components/downmusicPlayer/DownPlayer'
import SearchResults from '@/components/navbar/searchBar/SearchResults'
import Container from '@/components/downmusicPlayer/detailPlayer/Container'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthContext>
        <Theme >
          <Navber/>
          <SearchResults/>
          <ToastContainer
      position="top-right"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme="dark"
      />
          
          {children}
       
        </Theme>
        {/* detailPlayer */}

        <Container/>
      
     {/* down songbar */}
      <DownPlayer/>

        </AuthContext>
       
        </Providers>
      </body>
    </html>
  )
}
